packages:
  - apps/*
  - packages/*

confirmModulesPurge: false
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
allowBuilds:
  '@sentry/cli': false
  esbuild: true
  mongodb-memory-server: true
  unrs-resolver: true
