"""Regenerate the compact SVG paths used by the FR-PUB-01 trust map.

Source: Natural Earth 1:50m land and 1:10m India-viewpoint admin-0 countries
(public domain). The India-viewpoint outline includes India's claimed territories.
https://github.com/nvkelso/natural-earth-vector/tree/master/geojson
No mapping library or runtime download is needed by the website.
"""

import json
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1] / "components" / "landing"
BASE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/"


def load(name):
    cached = ROOT / f"{name}.source.geojson"
    if cached.exists():
        return json.loads(cached.read_text(encoding="utf-8"))
    with urllib.request.urlopen(BASE + name + ".geojson", timeout=30) as response:
        return json.load(response)


def project(point):
    lon, lat = point
    return ((lon + 180) * 2, (75 - lat) * 2)


def area(points):
    return abs(sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(points, points[1:] + points[:1]))) / 2


def simplify(points, tolerance):
    """Keep visible bends of a ring with no third-party geometry package."""
    if len(points) <= 4:
        return points
    keep = {0, len(points) - 1}
    stack = [(0, len(points) - 1)]
    while stack:
        start, end = stack.pop()
        x0, y0 = points[start]
        x1, y1 = points[end]
        dx, dy = x1 - x0, y1 - y0
        length = dx * dx + dy * dy
        best_distance = tolerance * tolerance
        best_index = None
        for index in range(start + 1, end):
            x, y = points[index]
            t = 0 if length == 0 else max(0, min(1, ((x - x0) * dx + (y - y0) * dy) / length))
            distance = (x - x0 - t * dx) ** 2 + (y - y0 - t * dy) ** 2
            if distance > best_distance:
                best_distance, best_index = distance, index
        if best_index is not None:
            keep.add(best_index)
            stack.extend(((start, best_index), (best_index, end)))
    return [points[index] for index in sorted(keep)]


def rings(geometry):
    if geometry["type"] == "Polygon":
        yield from geometry["coordinates"]
    elif geometry["type"] == "MultiPolygon":
        for polygon in geometry["coordinates"]:
            yield from polygon


def path(features, min_area, tolerance):
    parts = []
    for feature in features:
        for ring in rings(feature["geometry"]):
            if any(abs(a[0] - b[0]) > 180 for a, b in zip(ring, ring[1:])):
                continue  # Natural Earth polygons at the antimeridian must not cross the stage.
            points = [project(point) for point in ring[:-1]]
            if len(points) < 3 or area(points) < min_area:
                continue
            points = simplify(points, tolerance)
            if len(points) < 3:
                continue
            first, *rest = points
            parts.append("M" + f"{first[0]:.1f} {first[1]:.1f}" + "".join(f"L{x:.1f} {y:.1f}" for x, y in rest) + "Z")
    return "".join(parts)


land = load("ne_50m_land")
countries = load("ne_10m_admin_0_countries_ind")
india = [feature for feature in countries["features"] if feature["properties"].get("ADMIN") == "India"]
assert len(india) == 1

coast_path = path(land["features"], min_area=0.8, tolerance=0.7)
india_path = path(india, min_area=0.2, tolerance=0.28)
assert len(coast_path) > 10000 and len(india_path) > 1000

output = ROOT / "world-vector.data.ts"
output.write_text(
    "/* Generated by apps/web/scripts/generate-world-vector.py.\n"
    " * Natural Earth 1:50m land and 1:10m India-viewpoint admin-0 countries; public domain.\n"
    " * https://github.com/nvkelso/natural-earth-vector/tree/master/geojson\n"
    " * Equirectangular x=(longitude+180)*2, y=(75-latitude)*2.\n"
    " */\n"
    + "export const WORLD_COAST_PATH = " + json.dumps(coast_path) + ";\n"
    + "export const INDIA_OUTLINE_PATH = " + json.dumps(india_path) + ";\n",
    encoding="utf-8",
)
print(f"Wrote {output.name}: coast {len(coast_path)} chars, India {len(india_path)} chars")
