export const VENDOR_IDENTIFIER_HMAC_SECRET = Symbol("VENDOR_IDENTIFIER_HMAC_SECRET");
export const VENDOR_MODEL_NAME = "Vendor";
export const STORAGE_ADAPTER = Symbol("STORAGE_ADAPTER");
export const VENDOR_UPLOAD_EXPIRY_SECONDS = 5 * 60;
