export const CLIENT_IDENTIFIER_HMAC_SECRET = Symbol("CLIENT_IDENTIFIER_HMAC_SECRET");
export const CLIENT_MODEL_NAME = "Client";
export const CLIENT_STORE = Symbol("CLIENT_STORE");
export const CLIENT_STORAGE_ADAPTER = Symbol("CLIENT_STORAGE_ADAPTER");
