export const AUDIT_LOG_MODEL_NAME = "AuditLog";
export const AUDIT_LOG_STORE = "AUDIT_LOG_STORE";
export const COMPANY_REVIEW_STORAGE_ADAPTER =
  "COMPANY_REVIEW_STORAGE_ADAPTER";
export const COMPANY_DOCUMENT_GET_EXPIRY_SECONDS = 5 * 60;
