export enum PayoutBatchState {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  PROCESSING = "PROCESSING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  RETRY_QUEUED = "RETRY_QUEUED",
  CANCELLED = "CANCELLED",
}
