export enum ProfileState {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  TEST_PENDING = "TEST_PENDING",
  TEST_PASSED = "TEST_PASSED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  MORE_INFO_NEEDED = "MORE_INFO_NEEDED",
}
