export enum ProfileSection {
  PERSONAL = "PERSONAL",
  EDUCATION = "EDUCATION",
  SKILLS = "SKILLS",
  LANGUAGES = "LANGUAGES",
  EXPERIENCE = "EXPERIENCE",
  SAMPLES = "SAMPLES",
  AVAILABILITY = "AVAILABILITY",
  RATE = "RATE",
}
