export enum TaskState {
  QUEUED = "QUEUED",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
  IN_QA = "IN_QA",
  AUTO_ACCEPT = "AUTO_ACCEPT",
  ACCEPTED = "ACCEPTED",
  REWORK = "REWORK",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}
